# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: git branch
        run: git branch -l

      # Runs a single command using the runners shell
      - name: Merge into deploy branch
        run: |
                git config user.email "dev@stibee.com"
                git config user.name "stibee-dev-bot"
                .github/scripts/current-sprint.sh "${{ github.head_ref }}"
      - name: find conflicted branches
        run: |
                echo "CONFLICTED_BRANCHES="$(.github/scripts/find_conflict_branches.sh "${{ github.head_ref }}")>>$GITHUB_REF;
                for i in ${{ env.CONFLICTED_BRANCHES }}; do
                        echo $i;
                done
        if: ${{ failure() }}
      - name: close pr
        uses: actions/github-script@0.2.0
        with:
                github-token: ${{ github.token }}
                script: |
                        const ref = "${{ github.ref }}"
                        const pull_number = Number(ref.split("/")[2])

                        await github.pulls.createReview({
                                ...context.repo,
                                pull_number,
                                body: "머지 실패.\n${{ env.CONFLICTED_BRANCHES }}",
                                event: "REQUEST_CHANGES"
                        })

                        await github.pulls.update({
                                ...context.repo,
                                pull_number,
                                state: "closed"
                        })

        if: ${{ failure() }}

      - name: message to slack
        run: |
                echo "${{ secrets.slack_url }}"
                curl ${{ secrets.slack_url }} -XPOST -d 'payload={\"text\": \"PR 머지가 실패했습니다.\"}'
        if: ${{ failure() }}
